services:
  postgres:
    image: postgres:16
    container_name: databaselab_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:7
    container_name: databaselab_mongodb
    ports:
      - "27017:27017"
